# Generated by Django 2.0.7 on 2018-07-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='learning_text',
            field=models.TextField(max_length=3000),
        ),
    ]
