# Generated by Django 2.0.7 on 2018-07-28 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0003_learning_learning_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 13, 15, 32, 953929, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learning',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 13, 15, 43, 321652, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
