# Generated by Django 2.0.7 on 2018-08-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0006_auto_20180728_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='learning_text',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='learning',
            name='tags',
            field=models.ManyToManyField(blank=True, to='learned.Tag'),
        ),
    ]
