# Generated by Django 2.2.4 on 2019-09-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0009_auto_20190903_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=9),
        ),
    ]
